### ISSUE TITLE
Как можно сгенерировать адреса из seed?

### ISSUE THREAD

**Issue by DevAza** [MinterTeam/minter-php-bip-44#2]
Здравствуйте!
Я хочу создать много адресов HD Wallet.
Но как из $HDKey вытащить адрес BIP кошелька?

Привожу код:

use BIP\BIP44;

$seed = 'bcffab2ee26426c09a8486215a07a1a4b6a6b71b0db1947575477f1e113b08cafbe9465d41eb06573d29f298245a80f2be3a215aeb69d8f4c606168c8d334cc8';

$HDKey = BIP44::fromMasterSeed($seed)->derive("m/44'/60'/0'/0/0");

**Comment by grkamil** [comment]
Здравствуйте, Вы имеете в виду BIP кошелек для блокчейна Minter ? Можете использовать https://github.com/MinterTeam/minter-php-sdk для этого.
